# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1e214d0a480cf16ad201b168d47f346ebdade40f0c4eb53c9288e60872a3f2e1e1f83c17fd22323300c7140a6c72d5e75d636141705f11febfe28342cbe6e613

test:
  secret_key_base: 1123e1305e6fb524ee82165922bcc9790974574534f016e079264fa53f0a5473057f3c409cf18932499313024e09dcc934501bae50c853c03f22ca8e317d19be

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
